apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourcare
annotations:
  kubernetes.io/change-cause: "Initial deployment of micro-ui-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-ui-app
  template:
    metadata:
      labels:
        app: micro-ui-app
    spec:
      containers:
        - name: container-1
          image: nginx:latest
          ports:
            - containerPort: 80
  
